name: Workflow Example
run-name: Running Workflow Example

on:
  push:
    branches:
      - main
    tags:
      - /.*/

jobs:
  Deploy-Test:
    name: Deploy Test
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
