name: Workflow Example
run-name: Running Workflow Example

on:
  push:
    branches:
      - main
    tags:
      - .*

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Install go-task
        run: npm install -g @go-task/cli
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Composer install
        run: composer install
  build:
    needs: setup
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: task build
