name: Workflow Example
run-name: Running Workflow Example

on:
  push:
    branches:
      - main
    tags:
      - /.*/

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install go-task
        run: npm install -g @go-task/cli
      - name: Build
        run: task build
